### ISSUE TITLE
Unable to make Windows installer work

### ISSUE THREAD

**Issue by willemdh** [francelabs/datafari#17]
Hello,

I just tried installing the Datafari_Setup.exe v1.1 for WIndows 64bit on a Windows Server 2012. The setup seemed to have finished succesfully, but when browsing to http://localhost:8080/datafari I get a 404 with "The requested resource is not available".

![image](https://cloud.githubusercontent.com/assets/6462991/7857592/e06b5730-0531-11e5-843d-20c913c33b79.png)

The Tomcat window seemd to hang on INFO: Server startup in 12257 ms.

Any tips how to troubleshoot this?

Thanks and grtz

Willem

**Comment by otavard** [comment]
The Windows version is not our priority for now. We advise to use Docker version of Datafari if you are on Windows.
