### ISSUE TITLE
Ubuntu 16.04.1 LTS incompatibility

### ISSUE THREAD

**Issue by cbonsig** [francelabs/datafari#35]
I think I've found an incompatibility with the current version of Ubuntu, related to a conflict between the Cassandra code in Datafari 3.0 and Python 2.7.12 that is used in Ubuntu 16.04.1

Summary: Datafari 3.0 installation is partially successful in a fresh Ununtu 16.04.1 LTS installation. The main search page appears, but attempts to login to the admin page fail with a username/password error. Watching the logs during login attempts, catalina.out complains that:

> com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace 'datafari' does not exist

Attempting to investigate this by the command line utility cqlsh (/opt/datafari/cassandra/bin/cqlsh) results in the error:

> Connection error: ('Unable to connect to any servers', {'127.0.0.1': TypeError('ref() does not take keyword arguments',)})

This seems to be a symptom of [CASSANDRA-11850](https://issues.apache.org/jira/browse/CASSANDRA-11850), related to an incompatibility with Python 2.7.11+. This issue has been patched and merged into master branch, but the fix does not seem to yet be incorporated into Datafari.

If I could figure out what to change where, I'd create a pull request, but I'm afraid this is a bit beyond my abilities. Hope there are enough clues here to understand the issue, and recommend a fix.

Thanks for all the effort on this project, I'm eager to get it running!

**Comment by cbonsig** [comment]
In case others face this same issue: I abandoned Ubuntu 16.04, and started over with a fresh install of Debian 7.11, and that was successful. I did run into a problem when starting Datafari, with an error

`GLIBC_2.14 not found`

This workaround was successful:

```
Edit:  /etc/apt/sources.list
Add: deb http://http.us.debian.org/debian/ testing non-free contrib main
apt-get update
apt-get install libc6-dev
```

**Comment by otavard** [comment]
Hi Craig,

Thanks for your detailed report. We will try to reproduce the issue you mentioned on Ubuntu 16.04 and let you know.

For the lib not found on Debian, yes it is a mandatory package to install.
The requirements on the readme file are : 
Debian environment : requires curl, debconf, unzip, sudo, libc6-dev

Enjoy Datafari !

**Comment by cbonsig** [comment]
Regarding the Debian lib -- After initially installing Debian 7.11, I did run
`apt-get install curl debconf unzip libc6-dev`
I believe that everything installed successfully. After receiving the GLIBC_2.14 error noted above, I added the above note line to sources.list, ran the update and install, and then datafari started without complaints. I think there might have been version problem with the original libc6-dev package.

**Comment by otavard** [comment]
Hi,
Thanks for the reporting. Indeed for Debian 7, the version of the libc6 is too old in the stable repo.
We will update the documentation with your workaround for Debian 7.
On the other hand, in Debian 8, the libc6 lib in the standard repo is OK.

Best regards,

Olivier

**Comment by cbonsig** [comment]
Thanks, that's good to know. It would be helpful to recommend at least one recommended distro and point release in README.txt (it currently says "Debian7 or higher").

**Comment by alainsanguinetti** [comment]
Hello, I think upgrading to cassandra 3.9 could solve the problem.

**Comment by francelabs** [comment]
We use now Cassandra 3.10 in Datafari 4. The issue is not present anymore.
