### ISSUE TITLE
debian7 ant build script fails

### ISSUE THREAD

**Issue by cbonsig** [francelabs/datafari#36]
Trying to build from source on Debian 8.6, using source cloned from the main branch:

```
user@host:~/dev/datafari/debian7$ ant all
Buildfile: /home/user/dev/datafari/debian7/build.xml

copyBinaries:

BUILD FAILED
/home/user/dev/datafari/debian7/build.xml:133: /home/user/dev/datafari/datafari-tomcat/target/dist/tomcat does not exist.
```

It appears that the source directories in build.xml do not match the tree structure in the main branch. The source directory values contain ".../target/..." or ".../target/dist/..." while the main branch does not.

```
    <!-- Source directories -->
    <property name="elk.src.dir" value="${project.dir}/datafari-elk/target/dist/elk" />
    <property name="tomcat.src.dir" value="${project.dir}/datafari-tomcat/target/dist/tomcat" />
    <property name="solr.src.dir" value="${project.dir}/datafari-solr/target/dist/solr" />
    <property name="tika-config.src.dir" value="${project.dir}/datafari-tika-config/target" />
    <property name="datafari.src.dir" value="${project.dir}/datafari-core/target" />
    <property name="jena.src.dir" value="${project.dir}/datafari-jena/target" />
    <property name="mcf.src.dir" value="${project.dir}/datafari-mcf/target/dist/mcf" />
    <property name="realm.src.dir" value="${project.dir}/datafari-realm/target" />
    <property name="updateprocessor.src.dir" value="${project.dir}/datafari-updateprocessor/target" />
    <property name="datafarihandler.src.dir" value="${project.dir}/datafari-handler/target" />
    <property name="mcf-scripts.src.dir" value="${project.dir}/datafari-mcf-scripts/target" />
    <property name="cassandra.src.dir" value="${project.dir}/datafari-cassandra/target/dist/cassandra" />
    <property name="zookeeper.src.dir" value="${project.dir}/datafari-zookeeper/target/dist/zookeeper" />
    <property name="bin.src.dir" value="${project.dir}/bin" />
```

I tried changing ${project.dir}/datafari-tomcat/target/dist/tomcat to ${project.dir}/datafari-tomcat/ which resolves this specific error, then changing the other source directory values similarly, but continued to encounter other errors, then gave up. 

Any advice on how to make this work?

**Comment by francelabs** [comment]
Hi, sorry for the very late reply

the problem here is, I think, that you forgot to compile the whole projet by running the command "mvn clean install" at the root. Of course you need to have maven installed on your machine to do so.

**Comment by cbonsig** [comment]
Thanks for the reply, and the advice. I will give this a try during the holidays, and I'll comment back here with my results.
