### ISSUE TITLE
check pom.xml for 3.2.0 entries

### ISSUE THREAD

**Issue by marlemion** [francelabs/datafari#40]
Hi, I tried to build the 3.2.1 version, but got errors from maven due to 3.2.0 dependencies.

After a

`find ./ -type f -exec -name "pom.xml" sed -i 's/3\.2\.0/3\.2\.1/g' {} \;`

everything went fine. So there must be some pom.xml still having wrong version numbers present.

**Comment by otavard** [comment]
Hi marmelion,

Thank you for pointing that. You are right. We committed the right version number in the pom files in the master branch. We plan to release the 3.2.2 version for fixing that.

Best regards,

Olivier
