### ISSUE TITLE
Upload to MCF in datafari 4.0 not possible anymore

### ISSUE THREAD

**Issue by marlemion** [francelabs/datafari#42]
I have automated my version-changing process and so far, the uploading process (on the command line) worked for me. With datafari 4.0 I get a:

`<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.4 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 400 - Bad json: null</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Bad json: null</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><hr class="line"><h3>Apache Tomcat/8.5.4</h3></body></html>{ "userID":admin, "password":XXXXXX }`

Hence, none of the latter commands for uploading my MCF configuration works anymore. As I have quite a big configuration, I would rather not add it by hands again.

The JSON langugage does not seem to have changed. Any clue where the culprit lies?

**Comment by otavard** [comment]
Hello,
Did you have the same issue on Datafari 4.1 or was it ok ?

Best regards,
Olivier
