### ISSUE TITLE
Installing 4.0.2 on Debian Jessie

### ISSUE THREAD

**Issue by cbonsig** [francelabs/datafari#43]
I had previously installed Datafari 3.x in a development environment, mainly to index and search a Windows file system.  I just installed 4.0.2 on Debian Jessie 8.9 using the .deb package. Hardware is a VM with 16GB RAM. Before doing so, I moved the previous installation from /opt/datafari to /opt/datafari3 to avoid any conflicts with the old version. Just wanted to report here on my experience in case it is helpful for the developers or other users.

- Java 8 dependency: "Elasticsearch requires at least Java 8 but your Java version from /usr/bin/java does not meet this requirement" ... I wasn't sure if OpenJDK would be sufficient. I resolved this by following these instructions to install the Oracle Java 8 JRE. https://linux-tips.com/t/how-to-install-java-8-on-debian-jessie/349

- When starting up Datafari for the first time (start-datafari.sh), the script failed with the error "Fail to reach Elasticsearch on localhost:9200 Please check your network connection and, in case a proxy is configured, that a proxy exception exists for 'localhost' and '127.0.0.1’ !". I looked at the code in the script, and increased the wait from 10 to 1000 (I see in the current branch it is set to 15, maybe that would have been enough) https://github.com/francelabs/datafari/blob/116e795546a0ec518c12a91de6f4a74cb61898a1/debian7/bin/start-datafari.sh#L54 ... With this change, I was able to get into the Elasticsearch startup process.

- Elasticsearch got a bit farther along, then the script stalled again. The last console message was something to the effect of status changing from red to yellow. After some more log checking, I saw multiple errors kibana errors "mapper [hits] cannot be changed from type [long] to [integer]". The same error also mentioned "timelion".  This lead me here: https://github.com/elastic/kibana/issues/9888 ... which lead me to try `curl -XDELETE http://localhost:9200/.kibana` ... I do not understand any of this, but am grateful that it seemed to solve whatever the problem was.

- After the installation seemed to have successfully completed, I was unable to login to the admin console. The default user/password (admin/admin) gave unknown user or password error. Log checking revealed this error `Error initializing Cassandra client com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace ‘datafari’ does not exist` ... To solve this, I found my way to the cqlsh shell, which I had learned about in https://github.com/francelabs/datafari/issues/35 ... I launched /opt/datafari/cassandra/bin/cqlsh and gave the command `source /opt/datafari/bin/common/config/cassandra/tables` ... This did the trick. After a restart, I was able to login.

- Finally, I encountered some OOM Solr crashes after indexing got started. Resolved by changing the memory settings in /opt/datafari/solr/bin/solr.in.sh: `SOLR_JAVA_MEM="-Xms4g -Xmx4g"`

Everything is now up and running, and 10,000+ documents have been indexed. Thanks for all the great work on Datafari!

**Comment by otavard** [comment]
Hi,

Sorry for the late answer.
Thanks for all your comments. 
We will create soon a documentation page on the Datafari wiki to mention the different potential issues in the startup script and the FAQ : https://datafari.atlassian.net/wiki/spaces/DATAFARI/pages/485818369/FAQ

Best regards,

Olivier
