### ISSUE TITLE
MCF should be downgraded to 2.9.1

### ISSUE THREAD

**Issue by marlemion** [francelabs/datafari#46]
Hi,

I ran into this bug introduced with MCF 2.10: https://issues.apache.org/jira/browse/CONNECTORS-1510

Basically, it lacks the check for non-existing MIME Types. In case of a file with no MIME Type, the MCF process runs in a loop and never gets out of it. Result is that no MCF job containing any files ever finishes until aborted.

This is IMHO a CRITICAL bug. I have reverted to MCF 2.9.1 and it runs flawlessly. I heavily recommend to you and your users to do the same.

Please add to your bunch of test repositories (you are testing your builds, aren't you?) at least one file not having a MIME Type. This would exclude future bugs being overlooked.

**Comment by otavard** [comment]
Hi,

Thanks for your report.
We already patched Datafari Enterprise Edition with the patch provided by MCF. Regarding the Community Edition, we plan to integrate MCF 2.11 for the end of the month when it is released.

We do test our builds, but we cannot test every case, and we rely on the integrated components self testing capabilities. Unfortunately, this one skipped through MCF quality process. We will integrate in our dataset some files without mime type in our tests protocole.
BTW We have not implemented end to end functionnality testing as Selenium yet, we would gladly welcome your contribution if you feel like it.

Best regards,

Olivier
