### ISSUE TITLE
How to change "Source" facet

### ISSUE THREAD

**Issue by cbonsig** [francelabs/datafari#47]
I can not figure out how the "Source" facet gets set to "web" for all documents. I would like to change the value of this parameter from "web" to a value that is set according to the job. It seems that I should be able to follow the instructions in https://datafari.atlassian.net/wiki/spaces/DATAFARI/pages/6651920/Manually+adding+facets+to+the+Datafari+UI but use the existing metadata parameter "source" instead of creating a new parameter. When I try this, though, the facet never shows the parameter value that I assign. Instead, the "Source" facet is always "web". Is the "Source" facet on the results page mapped to a parameter other than "source"? Any suggestion on how to accomplish this?

**Comment by cbonsig** [comment]
I never did figure this out, but I was able to work around the issue by creating a new parameter and modifying the UI code as explained on the "Manually adding facets..." page referenced above. The instructions for modifying the Solr schema are out of date, but I was able to use the web UI to create the new field. I would be glad to revise the wiki page, but I don't see how to do so.

**Comment by cbonsig** [comment]
Closing this because workaround is sufficient.

**Comment by bloubi** [comment]
Hi Craig,
thanks for the info. As for modifying the wiki page, there is no restriction as to who can do it, so it should work for you, let us know if you have any issues on that.

**Comment by cbonsig** [comment]
@bloubi Merci! I was not able to edit the page directly, but I was able to add some inline comments to describe the process that I used. https://datafari.atlassian.net/wiki/spaces/DATAFARI/pages/6651920/Manually+adding+facets+to+the+Datafari+UI
