### ISSUE TITLE
Wrong path datafari-manager.sh in start-datafari.sh

### ISSUE THREAD

**Issue by marlemion** [francelabs/datafari#48]
Right now the start-script only work correctly if executed while being in the start directory. However, if it is executed from somewhere else, datafari-manager.sh is not found.

Hence: datafari-manager.sh -> $DIR/datafari-manager.sh troughout start-datafari.sh

**Comment by bloubi** [comment]
Hi Marlemion,

same comment as for your other ticket, please create it in our jira.
