### ISSUE TITLE
Datafari in docker - No volume to backup config and database

### ISSUE THREAD

**Issue by gauthi3r** [francelabs/datafari#74]
Hi all,

i just setup datafari on docker with this command : "docker container run --name datafari -d -p 443:443 datafari/datafari:latest"

but when i config somes parameters, i lost them after an restart of my container.

what is the good volume config to keep the data even if the container is restarted ? 

Many thanks :)

**Comment by bloubi** [comment]
Hi @gauthi3r ,

thanks for highlighting this. Originally, we decided not to make the CE docker version persistent when restarting the container. But giving it a second thought, it would give you a bad perception of Datafari. Therefore, we have updated the container, and starting with the next version of Datafari (v5.4.1), a restarted Datafari container will keep its data. With regards to proper volumes configuration, this will be available later as many components of Datafari require volumes, so it's not something easy to setup. Here is the ticket related to your issue: [https://gitlab.datafari.com/datafari-community/datafari/-/issues/893](https://gitlab.datafari.com/datafari-community/datafari/-/issues/893)

Note that this problem does not occur with the EE edition, which has its own way to persist the containers.
