### ISSUE TITLE
Installing JCIFS-NG Connector doesnt work

### ISSUE THREAD

**Issue by Rene-Dankwart-Synatix** [francelabs/datafari#77]
Im trying to install the JCIFS-NG Connector but in the connectors.xml the line i am supposed to uncomment doesnt exist and if i try to use the line given in the documentation (https://datafari.atlassian.net/wiki/spaces/DATAFARI/pages/662700036/Add+the+JCIFS-NG+Connector+to+Datafari+-+Community+Edition) i still get the same error.

when launching the init-datafari.sh i get the following error: "A required property is not correctly filled in datafari.properties file. The script will exit"

**Comment by bloubi** [comment]
Hi,

can you please explain which version of Datafari CE you are testing, and which OS you are running it ?

Regards,

Cedric

**Comment by Rene-Dankwart-Synatix** [comment]
I am running the datafari 6.0 on an Ubuntu 22.04 mashine.

**Comment by Rene-Dankwart-Synatix** [comment]
> Hi,
> 
> can you please explain which version of Datafari CE you are testing, and which OS you are running it ?
> 
> Regards,
> 
> Cedric

As stated above im running version 6.0 on Ubuntu 22.04.
did you found anything worth sharing?

**Comment by bloubi** [comment]
Hi,

we just tested again and it works fine. We are in particular puzzled by your statement: "but in the connectors.xml the line i am supposed to uncomment doesnt exist". This line does exist, so we wonder what you are actually using. Can you show us a screenshot of the connectors.xml that does not contain the line, and can you tell us which process you followed for the installation ? 

Regards,

Cedric

**Comment by Rene-Dankwart-Synatix** [comment]
It seems i have forgot to do package updates/upgrades which caused the problem...

still the line in the connectors.xml reads:
![image](https://github.com/francelabs/datafari/assets/166394987/307d2d77-1cac-42da-9e27-c15e125cbb98)
and the line in the guide reads: 
![image](https://github.com/francelabs/datafari/assets/166394987/9fa83a7d-7af6-4848-961e-80a475efb63f)

which led to confusion on my side.
Sorry for the unnecessary work.

**Comment by bloubi** [comment]
You're right, thanks for spotting the outdated screenshot in the wiki: I've just updated it to avoid confusion. Enjoy playing Datafari :)

**Comment by Rene-Dankwart-Synatix** [comment]
> You're right, thanks for spotting the outdated screenshot in the wiki: I've just updated it to avoid confusion. Enjoy playing Datafari :)

thank you for letting me know, but the written line above the screenshot in confluence is refering to the old line as well^^

**Comment by Rene-Dankwart-Synatix** [comment]
Edit: The problem didnt occur due to missing updates. I found out that the password of the admin during the initial start caused my problem.
After changing the passwort to one without special characters (in my case @, & and $) the "a required property is not correctly fileld in datafari.properties file" error did not happen anymore.

**Comment by bloubi** [comment]
> Edit: The problem didnt occur due to missing updates. I found out that the password of the admin during the initial start caused my problem. After changing the passwort to one without special characters (in my case @, & and $) the "a required property is not correctly fileld in datafari.properties file" error did not happen anymore.

Thanks for spotting this, we've created a ticket to work on it: https://gitlab.datafari.com/datafari-community/datafari/-/issues/996

About the documentation, I cannot find which written line you're mentioning that is still outdated ?

**Comment by Rene-Dankwart-Synatix** [comment]
> Thanks for spotting this, we've created a ticket to work on it: https://gitlab.datafari.com/datafari-community/datafari/-/issues/996
> 
> About the documentation, I cannot find which written line you're mentioning that is still outdated ?
Thanks.

Maybe it didnt update for me when i wrote the comment, its there now :)
